django/apps/cart/urls.py
from django.conf.urls import url
from cart import views


urlpatterns = [
    url(r'^add$', views.AddCartView.as_view(), name="add"),
    url(r'^$', views.CartInfoView.as_view(), name="info"),
    url(r'^update$', views.UpdateCartView.as_view(), name="update"),
    url(r'^delete$', views.DeleteCartView.as_view(), name="delete"),
]

django/apps/goods/urls.py
from django.conf.urls import url

from goods import views

urlpatterns = [
    url(r"^index$", views.IndexView.as_view(), name="index"),
    url(r"^detail/(?P<sku_id>\d+)$", views.DetailView.as_view(), name="detail"),
    url(r"^list/(?P<category_id>\d+)/(?P<page>\d+)$", views.ListView.as_view(), name="list"),
]

django/apps/orders/urls.py
from django.conf.urls import url
from orders import views


urlpatterns = [
    url(r"^place$", views.PlaceOrderView.as_view(), name="place"),
    url(r"^commit$", views.CommitOrderView.as_view(), name="commit"),
    url('^(?P<page>\d+)$', views.UserOrdersView.as_view(), name="info"),
    url('^comment/(?P<order_id>\d+)$', views.CommentView.as_view(), name="comment"),
    url('^pay$', views.PayView.as_view(), name="pay"),
    url('^check_pay$', views.CheckPayStatusView.as_view(), name="check_pay"),
]

django/apps/users/urls.py
from django.conf.urls import url

from users import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    # url(r'^register$', views.register, name="register"),
    url(r'^register$', views.RegisterView.as_view(), name="register"),
    url(r'^active/(?P<token>.+)$', views.ActiveView.as_view(), name="active"),
    url(r'^login$', views.LoginView.as_view(), name="login"),
    url(r'^logout$', views.LogoutView.as_view(), name="logout"),
    # url(r'^address$', login_required(views.AddressView.as_view()), name="address"),
    url(r'^address$', views.AddressView.as_view(), name="address"),
    url(r'^info$', views.UserInfoView.as_view(), name="info"),
]


解释一下 Django 和 Tornado 的关系、差别

Django 框架的核心组件有：
用于创建模型的对象关系映射为最终用户设计的完美管理界面一流的 URL  
设计设计者友好的模板语言缓存系统等等
它鼓励快速开发,并遵循MVC设计。Django遵守 BSD版权，最新发行版本是 Django1.4，
于2012年03月23日发布.Django的主要目的是简便、快速的开 发数据库驱动的网站。它强调代码复用,
多个组件可以很方便的以“插件” 形式服务于整个框架，Django有许多功能强大的第三方插件，你甚至可以
 很方便的开发出自己的工具包。这使得Django具有很强的可扩展性。
 它还 强调快速开发和DRY(Do Not RepeatYourself)原则。
Tornado 和现在的主流 Web 服务器框架（包括大多数Python 的框架）有 着明显的区别：
它是非阻塞式服务器，而且速度相当快。得利于其非阻塞 的方式和对epoll的运用，
Tornado 每秒可以处理数以千计的连接，这意味 着对于实时 Web服务来说，
Tornado 是一个理想的 Web 框架。我们开发这 个 Web 服务器的主要目的就是为了处理 
FriendFeed 的实时功能 ――在 
 FriendFeed 的应用里每一个活动用户都会保持着一个服务器连接。
 （关于 如何扩容 服务器，以处理数以千计的客户端的连接的问题。



新权限流程：
1. 配置url，写视图函数
2. admin后台录入权限，分配
3. 用户重新登录

权限的获取：
1. 用户登录,检测用户
2. 用户登录成功，则获取用户的权限列表（init_permission），并放置于session
3. 再次范围则中间件检测
获取权限就是在init_permission

django/django/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import users.urls
import goods.urls
import tinymce.urls
import haystack.urls
import cart.urls
import orders.urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include(tinymce.urls)),
    url(r'^search/', include(haystack.urls)),
    url(r'^users/', include(users.urls, namespace="users")),
    url(r'^cart/', include(cart.urls, namespace="cart")),
    url(r'^orders/', include(orders.urls, namespace="orders")),
    url(r'^', include(goods.urls, namespace="goods")),
]

django/apps/cart/models.py
from django.db import models

# Create your models here.

django/apps/cart/views.py
from django.shortcuts import render
from django.views.generic import View
from django.http import JsonResponse
from goods.models import GoodsSKU
from django_redis import get_redis_connection
import json

# Create your views here.


class AddCartView(View):
    """加入购物车"""
    def post(self, request):
        # # 判断用户是否登录
        # if not request.user.is_authenticated():
        #     # 用户未登录
        #     return JsonResponse({"code": 1, "message": "用户未登录"})

        # sku_id 商品id
        sku_id = request.POST.get("sku_id")
#后端严验证用户名和密码匹配后, 将用户信息存到session里面, response带上session_id给前端设置cookie就完了.
        # count 商品数量
        count = request.POST.get("count")

        # 检验参数
        if not all([sku_id, count]):
            return JsonResponse({"code": 2, "message": "参数不完整"})

        # 判断商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            # 表示商品不存在
            return JsonResponse({"code": 3, "message": "商品不存在"})

        # 判断count是整数
        try:
            count = int(count)
        except Exception:
            return JsonResponse({"code": 4, "message": "参数错误"})

        # 判断库存
        if count > sku.stock:
            return JsonResponse({"code": 5, "message": "库存不足"})

        if request.user.is_authenticated():
            # 如果用户已登录，则保存购物车数据到redis中

            # 用户id
            user_id = request.user.id

            # 操作redis，保存购物车数据
            # "cart_用户id"： {"sku_1": 10, "sku_2": 11}
            # 先尝试从用户的购物车中获取这个商品的数量
            # 如果购物车中不存在这个商品，则直接添加购物车记录
            # 否则，需要进行数量的累计，在添加到购物车记录中
            redis_conn = get_redis_connection("default")
            origin_count = redis_conn.hget("cart_%s" % user_id, sku_id)  # 原有数量

            if origin_count is not None:
                count += int(origin_count)

            redis_conn.hset("cart_%s" % user_id, sku_id, count)

            # 为了方便前端展示购物车数量，所以查询一下购物车总数
            cart_num = 0
            cart = redis_conn.hgetall("cart_%s" % user_id)
            for val in cart.values():
                cart_num += int(val)

            # 采用json返回给前端
            return JsonResponse({"code": 0, "message": "添加购物车成功", "cart_num": cart_num})
        else:
            # 如果用户未登录，则将购物车数据保存到cookie中
            # 尝试先从cookie的购物车信息中获取当前商品的记录
            cart_json = request.COOKIES.get("cart")  # 取出json字符串格式的购物车数据
            # 判断cart_json是否存在，用户可能从来没有操作过购物车
            if cart_json is not None:
                cart = json.loads(cart_json)  # cart是字典类型
                # { “sku_1”:10, “sku_2”: 20  }
            else:
                cart = {}

            # 如果cart中有这个商品的记录信息，
            if sku_id in cart:
                # 把数量进行求和,
                origin_count = cart[sku_id]  # 原有数量
                count += origin_count
            # 存放到cart字典中
            cart[sku_id] = count

            # 将cart购物车字典数据转换为json字符串
            new_cart_json = json.dumps(cart)

            # 计算购物车的商品总数
            cart_num = 0
            for val in cart.values():
                cart_num += val

            # 将购物车数据存放到cookie中
            response = JsonResponse({"code": 0, "message": "添加购物车成功", "cart_num": cart_num})

            response.set_cookie("cart", new_cart_json)

            # 返回处理结果
            return response


class CartInfoView(View):
    """购物车信息"""
    def get(self, request):
        """提供购物车页面"""
        # 业务逻辑， 查询购物车数据
        if not request.user.is_authenticated():
            # 如果用户未登录，从cookie获取数据
            cart_json = request.COOKIES.get("cart")
            if cart_json is not None:
                cart = json.loads(cart_json)
            else:
                # cookie中不存在购物车数据
                cart = {}
        else:
            # 如果用户已登录，从redis中获取数据
            redis_conn = get_redis_connection("default")
            user_id = request.user.id
            cart = redis_conn.hgetall("cart_%s" % user_id)

        # 遍历cart字典，形成模板所需要的数据
        skus = []
        total_amount = 0  # 总金额
        total_count = 0  # 总数量
        for sku_id, count in cart.items():
            try:
                sku = GoodsSKU.objects.get(id=sku_id)
            except GoodsSKU.DoesNotExist:
                # 商品不存在
                continue
            count = int(count)
            amount = sku.price * count  # Decimal
            sku.amount = amount  # 商品的金额
            sku.count = count  # 商品的数量
            skus.append(sku)
            total_amount += amount
            total_count += count

        # 返回处理结果, 渲染模板
        context = {
            "skus": skus,
            "total_amount": total_amount,
            "total_count": total_count
        }
        return render(request, "cart.html", context)


class UpdateCartView(View):
    """更新购物车数据"""
    def post(self, request):
        # 获取参数
        sku_id = request.POST.get("sku_id")  # 商品id
        count = request.POST.get("count")  # 商品数量

        # 校验参数
        if not all([sku_id, count]):
            return JsonResponse({"code": 1, "message": "参数不完整"})

        # 判断商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({"code": 2, "message": "商品不存在"})

        # count是否是整数
        try:
            count = int(count)
        except Exception:
            return JsonResponse({"code": 3, "message": "数量异常"})

        # 判断库存
        if count > sku.stock:
            return JsonResponse({"code": 4, "message": "库存不足"})

        # 保存购物车数据
        if not request.user.is_authenticated():
            # 如果用户未登录，保存在cookie中
            cart_json = request.COOKIES.get("cart")
            if cart_json is not None:
                cart = json.loads(cart_json)
            else:
                cart = {}
            # 将商品的数据保存到购物车中
            cart[sku_id] = count
            # 将购物车数据保存到cookie中
            response = JsonResponse({"code": 0, "message": "修改成功"})
            response.set_cookie("cart", json.dumps(cart))
            return response
        else:
            # 如果用户已登录，保存在redis中
            user_id = request.user.id
            redis_conn = get_redis_connection("default")
            redis_conn.hset("cart_%s" % user_id, sku_id, count)
            return JsonResponse({"code": 0, "message": "修改成功"})


class DeleteCartView(View):
    """删除购物车数据"""
    def post(self, request):
        sku_id = request.POST.get("sku_id")  # 商品id

        if not sku_id:
            return JsonResponse({"code": 1, "message": "参数缺少"})

        # 从购物车中删除数据
        if not request.user.is_authenticated():
            # 用户未登录 ，cookies
            cart_json = request.COOKIES.get("cart")
            if cart_json is not None:
                cart = json.loads(cart_json)
                # 如果购物车中有这个商品，则删除
                if sku_id in cart:
                    del cart[sku_id]
                    response = JsonResponse({"code": 0, "message": "删除成功"})
                    response.set_cookie("cart", json.dumps(cart))
                    return response
        else:
            # 用户已登录，redis
            redis_conn = get_redis_connection("default")
            user_id = request.user.id
            # 让redis删除sku_id对应的数据，如果redis中不存在，redis会忽略掉
            redis_conn.hdel("cart_%s" % user_id, sku_id)

        return JsonResponse({"code": 0, "message": "删除成功"})

django/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {% block topfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
    {% endblock %}
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
                {% if user.is_authenticated %}
				<div class="login_btn fl">
                    欢迎您：<em>{{ user.username }}</em>
					<span>|</span>
					<a href="{% url 'users:logout' %}">退出</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'users:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'users:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'users:info' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:info' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'orders:info' 1 %}">我的订单</a>
				</div>
			</div>
		</div>		
	</div>
    {% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
            <form action="/search/" method="get">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:info' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_num }}</div>
		</div>
	</div>
    {% endblock %}

    {% block body %}{% endblock %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
    {% block footer %}{% endblock %}
    {% block bottom_files %}{% endblock %}
</body>
</html>

django/templates/detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}天天生鲜-商品详情{% endblock %}

{% block body %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
                    {% for category in categorys %}
                    <li><a href="#" class="{{ category.logo }}">{{ category.name }}</a></li>
                    {% endfor %}
				</ul>
			</div>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="{% url 'goods:index' %}">全部分类</a>
		<span>></span>
		<a href="{% url 'goods:list' sku.category.id 1 %}">{{ sku.category.name }}</a>
		<span>></span>
		<a href="{% url 'goods:detail' sku.id %}">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="{{ sku.default_image.url }}"></div>
		<form method="post" action="{% url 'orders:place' %}">
			<input type="hidden" name="sku_ids" value="{{sku.id}}">
			{% csrf_token %}
		<div class="goods_detail_list fr">
			<h3>{{ sku.name}}</h3>
			<p>{{ sku.title }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ sku.price }}</em></span>
				<span class="show_unit">单  位：{{ sku.unit }}</span>
			</div>
            {% if goods_skus %}
            <div>
                <p>其他规格:</p>
                <ul>
                    {% for sku in goods_skus %}
                        <li><a href="{% url 'goods:detail' sku.id %}">{{ sku.price }}/{{ sku.unit }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" name="count" id="num_show" value="1">
					<a href="javascript:;" class="add fr" id="add">+</a>
					<a href="javascript:;" class="minus fr" id="minus">-</a>
				</div>
			</div>
			<div class="total">总价：<em>{{ sku.price }}</em>元</div>
			<div class="operate_btn">
				<input type="submit" class="buy_btn" id="buy_btn" value="立即购买">
				<a href="javascript:;" class="add_cart" sku_id="{{ sku.id }}" id="add_cart">加入购物车</a>
			</div>
		</div>
		</form>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
					{% for sku in new_skus %}
					<li>
						<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.default_image.url }}"></a>
						<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
						<div class="prize">￥{{ sku.price }}</div>
					</li>
					{% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li id="tag_detail" class="active">商品介绍</li>
				<li id="tag_comment">评论</li>
			</ul>

			<div class="tab_content" id="tab_detail">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{ sku.goods.desc|safe }}</dd>
				</dl>
			</div>

			<div class="tab_content" id="tab_comment" style="display: none;">
				{% for order in orders %}
				<dl>
					<dd>客户：{{ order.username }}&nbsp;&nbsp;&nbsp;时间：{{ order.ctime }}</dd>
					<dt>{{ order.comment }}</dt>
				</dl>
				<hr/>
				{% endfor %}
			</div>

		</div>
	</div>
{% endblock %}

{% block footer %}
	<div class="add_jump"></div>
{% endblock %}

{% block bottom_files %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.2.js' %}"></script>
	<script type="text/javascript">
		$("#tag_detail").click(function(){
			$("#tag_comment").removeClass("active");
			$(this).addClass("active");
			$("#tab_comment").hide();
			$("#tab_detail").show();
		});

		$("#tag_comment").click(function(){
			$("#tag_detail").removeClass("active");
			$(this).addClass("active");
			$("#tab_detail").hide();
			$("#tab_comment").show();
		});

		var $add_x = $('#add_cart').offset().top;
		var $add_y = $('#add_cart').offset().left;

		var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;

		$(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
		// 点击加入购物车
		$('#add_cart').click(function(){
		    // 将商品的id 和 数量发送给后端视图，保存到购物车数据中
			// 获取商品的id
			// 获取数量
            var req_data = {
                sku_id: $(this).attr("sku_id"),
				count: $("#num_show").val(),
				csrfmiddlewaretoken: "{{ csrf_token }}"
			};
			// 使用ajax向后端发送数据
            $.post("/cart/add", req_data, function (response_data) {
				// 根据response_data中的code决定处理效果
				if (0 == response_data.code) {
				    // 添加到购物车成功
					$(".add_jump").stop().animate({
                        'left': $to_y+7,
                        'top': $to_x+7},
                        "fast", function() {
                            $(".add_jump").fadeOut('fast',function(){
                                $('#show_count').html(response_data.cart_num);
                            });
                    });

				} else {
				    // 其他错误信息，alert展示
				    alert(response_data.message);
				}
            }, "json");
		});
		$("#add").click(function(){
			var num_show = $("#num_show").val();
			num_show = parseInt(num_show)
			num_show += 1;
			$("#num_show").val(num_show);
			var price = $(".show_pirze>em").html()
			price = parseFloat(price);
			var total = price * num_show;
			$(".total>em").html(total.toFixed(2));
		});
		$("#minus").click(function(){
			var num_show = $("#num_show").val();
			num_show = parseInt(num_show)
			num_show -= 1;
			if (num_show < 1){
				num_show = 1;
			}
			$("#num_show").val(num_show);
			var price = $(".show_pirze>em").html()
			price = parseFloat(price);
			var total = price * num_show;
			$(".total>em").html(total.toFixed(2));
		});
	</script>
{% endblock %}

django/templates/list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}天天生鲜-商品列表{% endblock %}

{% block body %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
                    {% for category in categorys %}
					<li><a href="{% url 'goods:list' category.id 1 %}" class="{{ category.logo }}">{{category.name}}</a></li>
					{% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="{% url 'goods:index' %}">全部分类</a>
		<span>></span>
		<a href="{% url 'goods:list' category.id 1 %}">{{ category.name }}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
					{% for sku in new_skus %}
					<li>
						<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.default_image.url}}"></a>
						<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
						<div class="prize">￥{{ sku.price }}</div>
					</li>
					{% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'goods:list' category.id 1 %}?sort=default" {% if sort == "default" %}class="active"{% endif %}>默认</a>
				<a href="{% url 'goods:list' category.id 1 %}?sort=price" {% if sort == "price" %}class="active"{% endif %}>价格</a>
				<a href="{% url 'goods:list' category.id 1 %}?sort=hot" {% if sort == "hot" %}class="active"{% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
				{% for sku in page_skus %}
				<li>
					<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.default_image.url }}"></a>
					<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ sku.price }}</span>
						<span class="unit">{{ sku.price }}/{{ sku.unit }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}
			</ul>

			<div class="pagenation">
				{% if page_skus.has_previous %}
				<a href="{% url 'goods:list' category.id page_skus.previous_page_number %}?sort={{sort}}"><上一页</a>
				{% endif %}

				{% for p in page_list %}
				<a href="{% url 'goods:list' category.id p %}?sort={{sort}}" {% if p == page_skus.number %}class="active"{% endif %}>{{p}}</a>
				{% endfor %}

				{% if page_skus.has_next %}
				<a href="{% url 'goods:list' category.id page_skus.next_page_number %}?sort={{sort}}">下一页></a>
				{% endif %}

			</div>
		</div>
	</div>
{% endblock %}

{% block footer %}
	<div class="popup_con">
		<div class="popup">
			<p>加入购物车成功！</p>
		</div>

		<div class="mask"></div>
	</div>
{% endblock %}

{% block bottom_files %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.2.js' %}"></script>
	<script type="text/javascript">
		$('.add_goods').click(function(){
            var req_data = {
                sku_id: $(this).attr("sku_id"),
                count: 1,
                csrfmiddlewaretoken: "{{ csrf_token }}"
            }
			$.post('/cart/add', req_data, function(data){
				if (0 == data.code) {
					$("#show_count").html(data.cart_num);
					$('.popup_con').fadeIn('fast', function() {
						setTimeout(function(){
							$('.popup_con').fadeOut('fast',function(){
							});
						},1000)
					});
				} else {
				    alert(data.message);
                }
			});
		});
	</script>
{% endblock %}

django/templates/order_comment.html
{% extends 'user_center_base.html' %}

{% load staticfiles %}

{% block title %}天天生鲜-用户中心{% endblock %}

{% block body %}
    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
				<li><a href="{% url 'users:info' %}">· 个人信息</a></li>
				<li><a href="{% url 'orders:info' 1 %}" class="active">· 全部订单</a></li>
				<li><a href="{% url 'users:address' %}">· 收货地址</a></li>
			</ul>
        </div>
        <div class="right_content clearfix">
            <h3 class="common_title2">订单评价</h3>
                <ul class="order_list_th w978 clearfix">
					<li class="col01">{{order.create_time}}</li>
					<li class="col02">订单号：{{order.order_id}}</li>
					<li class="col02 stress">{{order.status_name}}</li>
				</ul>
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="order_id" value="{{order.order_id}}">
                <input type="hidden" name="total_count" value="{{order.skus|length}}">
                {% for sku in order.skus %}
                <table class="order_list_table w980">
                    <tbody>
                        <tr>
                            <td width="80%">
                                <ul class="order_goods_list clearfix">
                                    <li class="col01"><img src="{{ sku.default_image.url }}"></li>
                                    <li class="col02">{{sku.name}}<em>{{sku.price}}/{{sku.unit}}</em></li>
                                    <li class="col03">{{sku.count}}</li>
                                </ul>
                            </td>
                            <td width="20%">{{sku.amount}}元</td>
                        </tr>
                    </tbody>
                </table>
                <div class="site_con">
                    <input type="hidden" name="sku_{{forloop.counter}}" value="{{sku.id}}">
                    <div class="form_group form_group2">
                        <label>评价内容：</label>
                        <textarea class="site_area" name="content_{{forloop.counter}}"></textarea>
                    </div>
                </div>
                {% endfor %}
                <input type="submit" name="" value="提交" class="info_submit">
            </form>
        </div>
    </div>
{% endblock %}

django/templates/user_center_base.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}天天生鲜-用户中心{% endblock %}

{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
            <form method="get" action="/search/">
			<input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			<input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
	</div>
{% endblock %}